spring.application.name=apply-custom-services
spring.main.banner-mode=off
logging.level.root[0]=info
logging.level.root[1]=debug
# set log of jdbc if you wanna see what statement is executing
logging.level.org.springframework.jdbc.core=trace
spring.config.import=classpath:info/db.properties
spring.datasource.driver-class-name=${jdbc.driver}
spring.datasource.url=${jdbc.url}
spring.datasource.username=${jdbc.username}
spring.datasource.password=${jdbc.password}