spring.application.name=apply-custom-services
spring.main.banner-mode=off
logging.level.root[0]=info
logging.level.root[1]=debug
server.port=6789
# set log of jdbc if you wanna see what statement is executing
logging.level.org.springframework.jdbc.core=trace
spring.config.import=classpath:info/db.properties
#Note! some name can't use for var as driver,username,password fix by add prefix!
#Note! mvn run and pass param only work on cmd not terminal
#mvn spring-boot:run -Dspring-boot.run.arguments="--mysql.driver=com.mysql.cj.jdbc.Driver , --mysql.url=jdbc:mysql://127.0.0.1:3306/apply_custom_services , --mysql.username=ttknp , --mysql.password=12345"
#java -jar apply-custom-services-0.0.1-SNAPSHOT.jar --mysql.url=jdbc:mysql://localhost:3306/apply_custom_services --mysql.username=ttknp --mysql.password=12345 --mysql.driver=com.mysql.cj.jdbc.Driver
spring.datasource.driver-class-name=${mysql.driver}
spring.datasource.url=${mysql.url}
spring.datasource.username=${mysql.username}
spring.datasource.password=${mysql.password}
#### Note!  when you build jar file as mvn clean install you have to skip test as "mvn clean install -Dmaven.test.skip=true" (run on cmd)